### 주간보고 마크다운 다운로드
GET http://localhost:8081/api/team-report/weekly/markdown?
    userId=38f54d40-1b13-4654-b739-dfdf6a708375
Authorization: Bearer {{accessToken}}

### 주간보고 엑셀 다운로드
GET http://localhost:8081/api/team-report/weekly/excel?
    userId=38f54d40-1b13-4654-b739-dfdf6a708375
Authorization: Bearer {{accessToken}}

### 주간보고 생성 확인
GET http://localhost:8081/api/report/chat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "chat": "오늘 오후 3시에는 고객 요청사항 분석 회의가 있고, 내일 오전 10시에는 기술 전략 수립 회의가 있어. 수요일 오후 1시에는 서비스 안정화 회의가 있고, 목요일 오전 9시에는 신규 기능 배포 회의가 있어. 금요일 오후 4시에는 팀 피드백 회의가 예정되어 있어."
}

### 전체 목록 조회
GET http://localhost:8081/api/report
Content-Type: application/json
Authorization: {{authorizationToken}}

