server:
  port: 8081
spring:
  application:
    name: whirlwind
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop        # DB 초기화 전략 (none, create, create-drop, update, validate)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력