spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
app:
  ollama:
    url: ${APP_OLLAMA_URL}
    model: ${APP_OLLAMA_MODEL}
    timeout-seconds: 30
  duckling:
    url: ${APP_DUCKLING_URL}
    timeout-seconds: 10
