version: '3.8'
services:
  frontend:
    image: neekly-frontend:${SPRING_PROFILES_ACTIVE}
    container_name: react-app
    ports:
      - "5173:5173"
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped